[package]
name = "ckb-notify"
version = "0.4.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
fnv = "1.0"
ckb-core = { path = "../core" }
channel = { package= "crossbeam-channel", version = "0.3" }
log = "0.4"
