[package]
name = "ckb-merkle-mountain-range"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
ckb-db = { path = "../../db" }

[dev-dependencies]
faster-hex = "0.3"
ckb-hash = { path = "../hash" }
