[package]
name = "ckb-pow"
version = "0.25.3-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
byteorder = "1.3.1"
ckb-types = { path = "../util/types" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types" }
serde = "1.0"
serde_derive = "1.0"
eaglesong = "0.1"
ckb-hash = { path = "../util/hash"}
ckb-crypto = { path = "../util/crypto" }
ckb-logger = { path = "../util/logger" }
