[package]
name = "ckb-chain-spec"
version = "0.21.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
faster-hex = "0.3"
ckb-types = { path = "../util/types" }
ckb-pow = { path = "../pow" }
ckb-resource = { path = "../resource" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types" }
ckb-dao-utils = { path = "../util/dao/utils" }
ckb-rational = { path = "../util/rational" }
ckb-crypto = { path = "../util/crypto"}
ckb-hash = { path = "../util/hash"}
failure = "0.1.5"
ckb-error = { path = "../error" }
