[package]
name = "ckb-agent-derive"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "^0.15.22", features = ["full", "extra-traits", "visit", "fold"] }
proc-macro2 = "0.4"
quote = "0.6"
proc-macro-crate = "0.1.3"
