[package]
name = "ckb-fee-policy"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
log = "0.4.6"
fnv = "1.0.6"
numext-fixed-hash = "0.1.4"
ckb-core = { path = "../core" }

