[package]
name = "ckb-tx-cache"
version = "0.19.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { path = "../types" }
lru-cache = { git = "https://github.com/nervosnetwork/lru-cache", rev = "a35fdb8" }
