[package]
name = "ckb-app-config"
version = "0.1.0"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
clap = { version = "2" }
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
log = "0.4"
logger = { path = "../../util/logger" }
sentry = "^0.15.2"
ckb-chain-spec = {path = "../../spec"}
ckb-network = { path = "../../network"}
ckb-rpc = { path = "../../rpc"}
ckb-miner = { path = "../../miner" }
ckb-db = { path = "../../db" }
ckb-pow = { path = "../../pow" }
ckb-resource = { path = "../../resource"}
ckb-instrument = { path = "../instrument", features = ["progress_bar"] }
ckb-shared = { path = "../../shared" }
ckb-sync = { path = "../../sync"}
build-info = { path = "../build-info" }

[dev-dependencies]
tempfile = "3.0"

